[package]
name = "proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.71"
proc-macro2 = "1.0.60"
quote = "1.0.28"
rand = "0.8.5"
syn = "2.0.18"
venial = "0.5.0"
codegen = { path = "../../codegen" }
